/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.HashMap;

public class App {
    public static void main(String[] args) {

        HashMap<Human, String> map = new HashMap<>();
        ArrayList<Human> array = new ArrayList<>();
        for (int i = 0; i < 40; i++) {
            Human zampolit = new Human(i);

            map.put(zampolit, "value" + i);
            array.add(zampolit);
            if (i % 5 == 0) {
                printHashMap(map);
            }
        }
    }

    private static void printHashMap(HashMap<?, ?> map) {
        try {
            Field tableField = HashMap.class.getDeclaredField("table");
            tableField.setAccessible(true);
            Object[] table = (Object[]) tableField.get(map);

            if (table == null) {
                System.out.println("The table is empty");
                return;
            }
            System.out.println("-".repeat(17));
            System.out.printf("The number of the buckets: %s\n", table.length);
            for (int i = 0; i < table.length; i++) {
                Object node = table[i];
                if (node != null) {
                    System.out.printf("The bucket type: %s\n",  node.getClass().getSimpleName());
                }
            }
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }
}
